In [28]:
import pandas as pd

In [29]:
df = pd.read_csv("nba_games.csv", index_col=0) # starts at column 0

In [30]:
df = df.sort_values("date") # sorts data frame by a single column in order of date

In [31]:
df = df.reset_index(drop=True) # resests index back to 0 and drops old index

In [32]:
del df["mp.1"]
del df["mp_opp.1"]
del df["index_opp"]  # deletes certain columns

In [33]:
def add_target(team): # 
    team["target"] = team["won"].shift(-1)
    return team

df = df.groupby("team", group_keys=False).apply(add_target) # creates data frame for each team

C:\Users\Taha  Hussaini\AppData\Local\Temp\ipykernel_12412\3915149810.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Taha  Hussaini\AppData\Local\Temp\ipykernel_12412\3915149810.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Taha  Hussaini\AppData\Local\Temp\ipykernel_12412\3915149810.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Taha  Hussaini\AppData\Local\Temp\ipykernel_12412\3915149810.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Taha  Hussaini\AppData\Local\Temp\ipykernel_12412\3915149810.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Taha  Hussaini\AppData\Local\Temp\ipykernel_12412\3915149810.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Taha  Hussaini\AppData\Local\Temp\ipykernel_12412\3915149810.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Taha  Hussaini\AppData\Local\Temp\ipykernel_12412\3915149810.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Taha  Hussaini\AppData\Local\Temp\ipykernel_12412\3915149810.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Taha  Hussaini\AppData\Local\Temp\ipykernel_12412\3915149810.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Taha  Hussaini\AppData\Local\Temp\ipykernel_12412\3915149810.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Taha  Hussaini\AppData\Local\Temp\ipykernel_12412\3915149810.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Taha  Hussaini\AppData\Local\Temp\ipykernel_12412\3915149810.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Taha  Hussaini\AppData\Local\Temp\ipykernel_12412\3915149810.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Taha  Hussaini\AppData\Local\Temp\ipykernel_12412\3915149810.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Taha  Hussaini\AppData\Local\Temp\ipykernel_12412\3915149810.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Taha  Hussaini\AppData\Local\Temp\ipykernel_12412\3915149810.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Taha  Hussaini\AppData\Local\Temp\ipykernel_12412\3915149810.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Taha  Hussaini\AppData\Local\Temp\ipykernel_12412\3915149810.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Taha  Hussaini\AppData\Local\Temp\ipykernel_12412\3915149810.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Taha  Hussaini\AppData\Local\Temp\ipykernel_12412\3915149810.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Taha  Hussaini\AppData\Local\Temp\ipykernel_12412\3915149810.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Taha  Hussaini\AppData\Local\Temp\ipykernel_12412\3915149810.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Taha  Hussaini\AppData\Local\Temp\ipykernel_12412\3915149810.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Taha  Hussaini\AppData\Local\Temp\ipykernel_12412\3915149810.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Taha  Hussaini\AppData\Local\Temp\ipykernel_12412\3915149810.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Taha  Hussaini\AppData\Local\Temp\ipykernel_12412\3915149810.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Taha  Hussaini\AppData\Local\Temp\ipykernel_12412\3915149810.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Taha  Hussaini\AppData\Local\Temp\ipykernel_12412\3915149810.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Taha  Hussaini\AppData\Local\Temp\ipykernel_12412\3915149810.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\Taha  Hussaini\AppData\Local\Temp\ipykernel_12412\3915149810.py:5: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df = df.groupby("team", group_keys=False).apply(add_target) # creates data frame for each team

In [34]:
df["team"] # teams list
df[df["team"] == "WAS"] # marksdown to specific team

          mp    fg    fga    fg%  ...  season        date    won  target
11     240.0  33.0   84.0  0.393  ...    2016  2015-10-28   True    True
63     240.0  35.0   68.0  0.515  ...    2016  2015-10-30   True   False
69     240.0  38.0   90.0  0.422  ...    2016  2015-10-31  False    True
124    240.0  42.0   87.0  0.483  ...    2016  2015-11-04   True   False
161    240.0  36.0   88.0  0.409  ...    2016  2015-11-06  False   False
...      ...   ...    ...    ...  ...     ...         ...    ...     ...
17471  240.0  38.0   82.0  0.463  ...    2022  2022-04-03  False    True
17483  240.0  56.0  101.0  0.554  ...    2022  2022-04-05   True   False
17510  240.0  42.0   86.0  0.488  ...    2022  2022-04-06  False   False
17538  240.0  35.0   69.0  0.507  ...    2022  2022-04-08  False   False
17558  240.0  42.0   94.0  0.447  ...    2022  2022-04-10  False     NaN

[580 rows x 148 columns]

In [35]:
df["target"][pd.isnull(df["target"])] = 2 # takes target, uses isnull func and replaces them with 2

C:\Users\Taha  Hussaini\AppData\Local\Temp\ipykernel_12412\1203645242.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["target"][pd.isnull(df["target"])] = 2 # takes target, uses isnull func and replaces them with 2
C:\Users\Taha  Hussaini\AppData\Local\Temp\ipykernel_12412\1203645242.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["target"][pd.isnull(df["target"])] = 2 # takes target, uses isnull func and replaces them with 2

In [36]:
df["target"] = df["target"].astype(int, errors="ignore") # converts boolean into ints

In [37]:
df["won"].value_counts()

won
False    8886
True     8886
Name: count, dtype: int64

In [38]:
df["target"].value_counts()

target
1    8872
0    8870
2      30
Name: count, dtype: int64

In [ ]:
nulls = pd.isnull(df).sum()
nulls = nulls[nulls > 0]
valid_columns = df.columns[~df.columns.isin(nulls.index)]
valid_columns
df = df[valid_columns].copy()

          mp    fg   fga    fg%  ...  season        date    won  target
0      240.0  35.0  83.0  0.422  ...    2016  2015-10-27  False       0
1      240.0  38.0  94.0  0.404  ...    2016  2015-10-27  False       1
2      240.0  37.0  87.0  0.425  ...    2016  2015-10-27   True       1
3      240.0  41.0  96.0  0.427  ...    2016  2015-10-27   True       1
4      240.0  37.0  82.0  0.451  ...    2016  2015-10-27  False       1
...      ...   ...   ...    ...  ...     ...         ...    ...     ...
17767  240.0  34.0  85.0  0.400  ...    2022  2022-06-10  False       0
17768  240.0  41.0  88.0  0.466  ...    2022  2022-06-13   True       1
17769  240.0  31.0  75.0  0.413  ...    2022  2022-06-13  False       0
17770  240.0  34.0  80.0  0.425  ...    2022  2022-06-16  False       2
17771  240.0  38.0  92.0  0.413  ...    2022  2022-06-16   True       2

[17772 rows x 142 columns]

In [40]:
from sklearn.model_selection import TimeSeriesSplit # will help split data
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.linear_model import RidgeClassifier # machine learning model

rr = RidgeClassifier(alpha=1)
split = TimeSeriesSplit(n_splits=3)

sfs = SequentialFeatureSelector(rr, n_features_to_select=30, direction="forward", cv=split)

In [41]:
removed_columns = ["season", "date", "won", "target", "team", "team_opp"]

In [42]:
selected_columns = df.columns[~df.columns.isin(removed_columns)] # ~deletes columns under certain condition

In [43]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df[selected_columns] = scaler.fit_transform(df[selected_columns])

In [45]:
sfs.fit(df[selected_columns], df["target"])

SequentialFeatureSelector(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
                          estimator=RidgeClassifier(alpha=1),
                          n_features_to_select=30)

In [47]:
predictors = list(selected_columns[sfs.get_support()]) # sfs.get_support is a boolean True or false that indexes values that are going to be used to train the model

In [ ]:
predictors

['mp',
 'fg%',
 '3p%',
 'orb',
 'ts%',
 'usg%',
 '3p%_max',
 'ft_max',
 'fta_max',
 '+/-_max',
 'drb%_max',
 'trb%_max',
 'tov%_max',
 'usg%_max',
 'mp_opp',
 'fg_opp',
 '3p_opp',
 'ft%_opp',
 'blk_opp',
 'usg%_opp',
 'fga_max_opp',
 '3p_max_opp',
 'ft_max_opp',
 'ft%_max_opp',
 'blk_max_opp',
 'pf_max_opp',
 'pts_max_opp',
 'drb%_max_opp',
 'blk%_max_opp',
 'usg%_max_opp']

In [51]:
def backtest(data, model, predictors, start=2, step=1): # splits data by season and uses past season to predict future
    all_predictions = [] # data frame for all predictions

    seasons = sorted(data["season"].unique())

    for i in range(start, len(seasons), step):
        season = season[i]

        train = data[data["season"] < season]
        test = data[data["season"] == season]

In [52]:
sorted(df["season"].unique())

[np.int64(2016),
 np.int64(2017),
 np.int64(2018),
 np.int64(2019),
 np.int64(2020),
 np.int64(2021),
 np.int64(2022)]